version: '3'
services:
    postgres:
        image: 'postgres:latest'
        environment:
            - POSTGRES_PASSWORD=root
    api:
        build:
            dockerfile: Dockerfile
            context: ./server
        volumes: 
            - /app/node_modules
            - ./server:/app
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=root
            - PGPORT=5432
        depends_on:
            - postgres
    nginx:
        build: 
            dockerfile: Dockerfile
            context: ./nginx
        ports:  
            - '3050:80'
        depends_on:
            - api