version: '3'
services:
    api:
        build:
            dockerfile: Dockerfile
            context: ./server
        volumes: 
            - /app/node_modules
            - ./server:/app
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
    
    nginx:
        build: 
            dockerfile: Dockerfile
            context: ./nginx
        ports:  
            - '3050:80'
        depends_on:
            - api